// Generated by scripts/extract-lexicon.mjs. Do not edit.
//
// Source: /Users/werner/github.com/wstein/flix-fork @ 48f7ae9
//   keywords     Lexer.scala, 'private val Keywords'
//   simpleTokens Lexer.scala, 'private val SimpleTokens'
//   operators    Lexer.scala, 'private val Operators'
//   annotations  Weeder2.scala, 'visitAnnotation'
//
// Regenerate with: npm run extract:lexicon

/** Every keyword the lexer recognises (84). */
export const KEYWORDS = [
  'Array#',
  'List#',
  'Map#',
  'Set#',
  'Static',
  'Univ',
  'Vector#',
  'alias',
  'and',
  'as',
  'case',
  'catch',
  'checked_cast',
  'checked_ecast',
  'choose',
  'choose*',
  'def',
  'discard',
  'eff',
  'else',
  'ematch',
  'enum',
  'false',
  'fix',
  'forA',
  'forM',
  'forall',
  'force',
  'foreach',
  'from',
  'handler',
  'if',
  'import',
  'inject',
  'instance',
  'instanceof',
  'into',
  'law',
  'lawful',
  'lazy',
  'let',
  'match',
  'mod',
  'mut',
  'new',
  'not',
  'null',
  'open_variant',
  'open_variant_as',
  'or',
  'par',
  'pquery',
  'project',
  'psolve',
  'pub',
  'query',
  'redef',
  'region',
  'restrictable',
  'run',
  'rvadd',
  'rvand',
  'rvnot',
  'rvsub',
  'sealed',
  'select',
  'solve',
  'spawn',
  'static',
  'struct',
  'super',
  'throw',
  'trait',
  'true',
  'try',
  'type',
  'unchecked_cast',
  'unsafe',
  'use',
  'where',
  'with',
  'xor',
  'xvar',
  'yield',
] as const;

/** A keyword spelling. Mapping this with `Record` makes an unclassified keyword a type error. */
export type Keyword = (typeof KEYWORDS)[number];

/** Tokens consumed regardless of the following character (17). */
export const SIMPLE_TOKENS = [
  '#',
  '#(',
  '#{',
  '#|',
  '(',
  ')',
  ',',
  ';',
  '???',
  '[',
  '\\',
  ']',
  '`',
  '{',
  '|#',
  '}',
  '~',
] as const;

/** Tokens consumed as long as no operator character follows (22). */
export const OPERATORS = [
  '!',
  '!=',
  '&',
  '*',
  '+',
  '-',
  ':',
  ':-',
  '::',
  ':::',
  '<',
  '<+>',
  '<-',
  '<=',
  '<=>',
  '=',
  '==',
  '=>',
  '>',
  '>=',
  '^',
  '|',
] as const;

/**
 * Annotations `Weeder2` accepts (17), without the leading `@`.
 *
 * The grammar deliberately does NOT enumerate these: `Lexer.acceptAnnotation` consumes
 * `@` followed by ASCII letters, so one rule covers every annotation that exists or will.
 * This list exists so the tests can prove each accepted annotation is scoped.
 */
export const ANNOTATIONS = [
  'CompileTest',
  'DefaultHandler',
  'Deprecated',
  'DontInline',
  'Experimental',
  'Export',
  'Inline',
  'Parallel',
  'ParallelWhenPure',
  'LoweringTargetDatalog',
  'LoweringTargetChannel',
  'Lazy',
  'LazyWhenPure',
  'Skip',
  'Test',
  'Tailrec',
  'Terminates',
] as const;
