    pub def add(x: Int32, y: Int32): Int32 = x + y
    def >>(f: a -> b, g: b -> c): a -> c = z -> g(f(z))
    law reflexivity: forall (x: a) . x == x
    enum Shape { case Circle(Int32) }
    struct Node[r] { value: Int32 }
    trait Eq[a]
    eff Console
    instance Eq[Shape]
    mod Foo.Bar.Baz
    type alias Grid = Vector[Vector[Int32]]
    let p = person->name
    let q = person -> name
    let _ = ∀x
    let $use = 1
    r.field
